# Mata pelajaran umum per jenjang (Kurikulum Merdeka)
SUBJECTS_BY_LEVEL = {
    'SD/MI': [
        'Pendidikan Agama dan Budi Pekerti',
        'Pendidikan Pancasila dan Kewarganegaraan',
        'Bahasa Indonesia',
        'Matematika',
        'Ilmu Pengetahuan Alam',
        'Ilmu Pengetahuan Sosial',
        'Seni Budaya dan Prakarya',
        'Pendidikan Jasmani, Olahraga, dan Kesehatan',
        'Bahasa Inggris',
    ],
    'SMP/MTs': [
        'Pendidikan Agama dan Budi Pekerti',
        'Pendidikan Pancasila dan Kewarganegaraan',
        'Bahasa Indonesia',
        'Bahasa Inggris',
        'Matematika',
        'Ilmu Pengetahuan Alam',
        'Ilmu Pengetahuan Sosial',
        'Seni Budaya',
        'Pendidikan Jasmani, Olahraga, dan Kesehatan',
        'Prakarya',
        'Informatika',
    ],
    'SMA/MA': [
        'Pendidikan Agama dan Budi Pekerti',
        'Pendidikan Pancasila dan Kewarganegaraan',
        'Bahasa Indonesia',
        'Bahasa Inggris',
        'Matematika',
        'Matematika Peminatan',
        'Fisika',
        'Kimia',
        'Biologi',
        'Sejarah',
        'Geografi',
        'Ekonomi',
        'Sosiologi',
        'Seni Budaya',
        'Pendidikan Jasmani, Olahraga, dan Kesehatan',
        'Prakarya dan Kewirausahaan',
        'Informatika',
    ],
}
